# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_window_ui.ui'
#
# Created: Sat Nov 19 23:58:06 2016
#      by: pyside2-uic  running on PySide2 2.0.0~alpha0
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 610)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/appIcon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setSpacing(4)
        self.verticalLayout.setContentsMargins(6, 6, 6, 6)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.uiBTN_filter = QtWidgets.QToolButton(self.centralwidget)
        self.uiBTN_filter.setMinimumSize(QtCore.QSize(24, 24))
        self.uiBTN_filter.setMaximumSize(QtCore.QSize(24, 24))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/filter_disabled.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon1.addPixmap(QtGui.QPixmap(":/icons/filter_active.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.uiBTN_filter.setIcon(icon1)
        self.uiBTN_filter.setIconSize(QtCore.QSize(18, 18))
        self.uiBTN_filter.setCheckable(True)
        self.uiBTN_filter.setObjectName("uiBTN_filter")
        self.horizontalLayout.addWidget(self.uiBTN_filter)
        self.uiLED_filter = QtWidgets.QLineEdit(self.centralwidget)
        self.uiLED_filter.setMinimumSize(QtCore.QSize(0, 24))
        self.uiLED_filter.setObjectName("uiLED_filter")
        self.horizontalLayout.addWidget(self.uiLED_filter)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.uiTBL_textures = QtWidgets.QTableView(self.centralwidget)
        self.uiTBL_textures.setContextMenuPolicy(QtCore.Qt.ActionsContextMenu)
        self.uiTBL_textures.setEditTriggers(QtWidgets.QAbstractItemView.DoubleClicked)
        self.uiTBL_textures.setAlternatingRowColors(True)
        self.uiTBL_textures.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.uiTBL_textures.setTextElideMode(QtCore.Qt.ElideLeft)
        self.uiTBL_textures.setHorizontalScrollMode(QtWidgets.QAbstractItemView.ScrollPerPixel)
        self.uiTBL_textures.setShowGrid(False)
        self.uiTBL_textures.setSortingEnabled(True)
        self.uiTBL_textures.setObjectName("uiTBL_textures")
        self.uiTBL_textures.horizontalHeader().setSortIndicatorShown(True)
        self.uiTBL_textures.horizontalHeader().setStretchLastSection(True)
        self.uiTBL_textures.verticalHeader().setVisible(False)
        self.uiTBL_textures.verticalHeader().setDefaultSectionSize(15)
        self.uiTBL_textures.verticalHeader().setMinimumSectionSize(15)
        self.verticalLayout.addWidget(self.uiTBL_textures)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuActions = QtWidgets.QMenu(self.menubar)
        self.menuActions.setObjectName("menuActions")
        self.menuEdit = QtWidgets.QMenu(self.menubar)
        self.menuEdit.setObjectName("menuEdit")
        self.menuOptions = QtWidgets.QMenu(self.menubar)
        self.menuOptions.setObjectName("menuOptions")
        self.menuSelect = QtWidgets.QMenu(self.menubar)
        self.menuSelect.setObjectName("menuSelect")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.toolBar = QtWidgets.QToolBar(MainWindow)
        self.toolBar.setMovable(False)
        self.toolBar.setIconSize(QtCore.QSize(24, 24))
        self.toolBar.setFloatable(False)
        self.toolBar.setObjectName("toolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.uiACT_refresh = QtWidgets.QAction(MainWindow)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icons/refresh.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.uiACT_refresh.setIcon(icon2)
        self.uiACT_refresh.setObjectName("uiACT_refresh")
        self.uiACT_exit = QtWidgets.QAction(MainWindow)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/icons/exit.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.uiACT_exit.setIcon(icon3)
        self.uiACT_exit.setObjectName("uiACT_exit")
        self.uiACT_retarget = QtWidgets.QAction(MainWindow)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/icons/retarget.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.uiACT_retarget.setIcon(icon4)
        self.uiACT_retarget.setObjectName("uiACT_retarget")
        self.uiACT_copyMove = QtWidgets.QAction(MainWindow)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/icons/copy_move.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.uiACT_copyMove.setIcon(icon5)
        self.uiACT_copyMove.setObjectName("uiACT_copyMove")
        self.uiACT_searchReplace = QtWidgets.QAction(MainWindow)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/icons/replace.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.uiACT_searchReplace.setIcon(icon6)
        self.uiACT_searchReplace.setObjectName("uiACT_searchReplace")
        self.uiACT_copyFullPath = QtWidgets.QAction(MainWindow)
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(":/icons/copy1.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.uiACT_copyFullPath.setIcon(icon7)
        self.uiACT_copyFullPath.setObjectName("uiACT_copyFullPath")
        self.uiACT_copyFilename = QtWidgets.QAction(MainWindow)
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(":/icons/copy2.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.uiACT_copyFilename.setIcon(icon8)
        self.uiACT_copyFilename.setObjectName("uiACT_copyFilename")
        self.uiACT_selectAssigned = QtWidgets.QAction(MainWindow)
        self.uiACT_selectAssigned.setCheckable(True)
        self.uiACT_selectAssigned.setObjectName("uiACT_selectAssigned")
        self.uiACT_collapseRepetitions = QtWidgets.QAction(MainWindow)
        self.uiACT_collapseRepetitions.setCheckable(True)
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(":/icons/collapse.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.uiACT_collapseRepetitions.setIcon(icon9)
        self.uiACT_collapseRepetitions.setObjectName("uiACT_collapseRepetitions")
        self.uiACT_selectAll = QtWidgets.QAction(MainWindow)
        self.uiACT_selectAll.setObjectName("uiACT_selectAll")
        self.uiACT_selectNone = QtWidgets.QAction(MainWindow)
        self.uiACT_selectNone.setObjectName("uiACT_selectNone")
        self.uiACT_selectInvert = QtWidgets.QAction(MainWindow)
        self.uiACT_selectInvert.setObjectName("uiACT_selectInvert")
        self.uiACT_selectTextureNode = QtWidgets.QAction(MainWindow)
        self.uiACT_selectTextureNode.setCheckable(True)
        self.uiACT_selectTextureNode.setObjectName("uiACT_selectTextureNode")
        self.uiACT_selectNothing = QtWidgets.QAction(MainWindow)
        self.uiACT_selectNothing.setCheckable(True)
        self.uiACT_selectNothing.setObjectName("uiACT_selectNothing")
        self.uiACT_copy = QtWidgets.QAction(MainWindow)
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap(":/icons/copy.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.uiACT_copy.setIcon(icon10)
        self.uiACT_copy.setObjectName("uiACT_copy")
        self.uiACT_paste = QtWidgets.QAction(MainWindow)
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap(":/icons/paste.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.uiACT_paste.setIcon(icon11)
        self.uiACT_paste.setObjectName("uiACT_paste")
        self.uiACT_analyzeSelection = QtWidgets.QAction(MainWindow)
        self.uiACT_analyzeSelection.setCheckable(True)
        icon12 = QtGui.QIcon()
        icon12.addPixmap(QtGui.QPixmap(":/icons/lock_to_selection.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.uiACT_analyzeSelection.setIcon(icon12)
        self.uiACT_analyzeSelection.setObjectName("uiACT_analyzeSelection")
        self.uiACT_deleteUnusedShadingNodes = QtWidgets.QAction(MainWindow)
        self.uiACT_deleteUnusedShadingNodes.setObjectName("uiACT_deleteUnusedShadingNodes")
        self.menuFile.addAction(self.uiACT_refresh)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.uiACT_exit)
        self.menuActions.addAction(self.uiACT_deleteUnusedShadingNodes)
        self.menuActions.addSeparator()
        self.menuActions.addAction(self.uiACT_copyMove)
        self.menuActions.addAction(self.uiACT_retarget)
        self.menuActions.addAction(self.uiACT_searchReplace)
        self.menuEdit.addAction(self.uiACT_copy)
        self.menuEdit.addAction(self.uiACT_paste)
        self.menuEdit.addSeparator()
        self.menuEdit.addAction(self.uiACT_copyFullPath)
        self.menuEdit.addAction(self.uiACT_copyFilename)
        self.menuOptions.addAction(self.uiACT_collapseRepetitions)
        self.menuOptions.addAction(self.uiACT_analyzeSelection)
        self.menuOptions.addSeparator()
        self.menuOptions.addAction(self.uiACT_selectNothing)
        self.menuOptions.addAction(self.uiACT_selectAssigned)
        self.menuOptions.addAction(self.uiACT_selectTextureNode)
        self.menuSelect.addAction(self.uiACT_selectAll)
        self.menuSelect.addAction(self.uiACT_selectInvert)
        self.menuSelect.addAction(self.uiACT_selectNone)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuEdit.menuAction())
        self.menubar.addAction(self.menuSelect.menuAction())
        self.menubar.addAction(self.menuActions.menuAction())
        self.menubar.addAction(self.menuOptions.menuAction())
        self.toolBar.addAction(self.uiACT_refresh)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.uiACT_analyzeSelection)
        self.toolBar.addAction(self.uiACT_collapseRepetitions)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.uiACT_copyFullPath)
        self.toolBar.addAction(self.uiACT_copyFilename)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.uiACT_copy)
        self.toolBar.addAction(self.uiACT_paste)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.uiACT_copyMove)
        self.toolBar.addAction(self.uiACT_retarget)
        self.toolBar.addAction(self.uiACT_searchReplace)

        self.retranslateUi(MainWindow)
        QtCore.QObject.connect(self.uiACT_exit, QtCore.SIGNAL("triggered()"), MainWindow.close)
        QtCore.QObject.connect(self.uiACT_refresh, QtCore.SIGNAL("triggered()"), MainWindow.onRefreshTriggered)
        QtCore.QObject.connect(self.uiACT_copyFullPath, QtCore.SIGNAL("triggered()"), MainWindow.onCopyFullPathTriggered)
        QtCore.QObject.connect(self.uiACT_copyFilename, QtCore.SIGNAL("triggered()"), MainWindow.onCopyFilenameTriggered)
        QtCore.QObject.connect(self.uiACT_copyMove, QtCore.SIGNAL("triggered()"), MainWindow.onCopyMoveTriggered)
        QtCore.QObject.connect(self.uiACT_retarget, QtCore.SIGNAL("triggered()"), MainWindow.onRetargetTriggered)
        QtCore.QObject.connect(self.uiACT_searchReplace, QtCore.SIGNAL("triggered()"), MainWindow.onSearchReplaceTriggered)
        QtCore.QObject.connect(self.uiLED_filter, QtCore.SIGNAL("textChanged(QString)"), MainWindow.onFilterTextChanged)
        QtCore.QObject.connect(self.uiBTN_filter, QtCore.SIGNAL("toggled(bool)"), MainWindow.onFilterButtonToggled)
        QtCore.QObject.connect(self.uiACT_selectAll, QtCore.SIGNAL("triggered()"), MainWindow.onSelectAllTriggered)
        QtCore.QObject.connect(self.uiACT_selectInvert, QtCore.SIGNAL("triggered()"), MainWindow.onSelectInvertTriggered)
        QtCore.QObject.connect(self.uiACT_selectNone, QtCore.SIGNAL("triggered()"), MainWindow.onSelectNoneTriggered)
        QtCore.QObject.connect(self.uiACT_collapseRepetitions, QtCore.SIGNAL("toggled(bool)"), MainWindow.onCollapseRepetitionsToggled)
        QtCore.QObject.connect(self.uiACT_selectTextureNode, QtCore.SIGNAL("toggled(bool)"), MainWindow.onChangeSelectionBehaviour)
        QtCore.QObject.connect(self.uiACT_selectAssigned, QtCore.SIGNAL("toggled(bool)"), MainWindow.onChangeSelectionBehaviour)
        QtCore.QObject.connect(self.uiACT_copy, QtCore.SIGNAL("triggered()"), MainWindow.onCopyTriggered)
        QtCore.QObject.connect(self.uiACT_paste, QtCore.SIGNAL("triggered()"), MainWindow.onPasteTriggered)
        QtCore.QObject.connect(self.uiACT_analyzeSelection, QtCore.SIGNAL("toggled(bool)"), MainWindow.onAnalyzeSelectionToggled)
        QtCore.QObject.connect(self.uiACT_deleteUnusedShadingNodes, QtCore.SIGNAL("triggered()"), MainWindow.onDeleteUnusedShadingNodesTriggered)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.uiTBL_textures, self.uiLED_filter)
        MainWindow.setTabOrder(self.uiLED_filter, self.uiBTN_filter)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtWidgets.QApplication.translate("MainWindow", "Texture Manager", None, -1))
        self.uiBTN_filter.setText(QtWidgets.QApplication.translate("MainWindow", "...", None, -1))
        self.menuFile.setTitle(QtWidgets.QApplication.translate("MainWindow", "File", None, -1))
        self.menuActions.setTitle(QtWidgets.QApplication.translate("MainWindow", "Actions", None, -1))
        self.menuEdit.setTitle(QtWidgets.QApplication.translate("MainWindow", "Edit", None, -1))
        self.menuOptions.setTitle(QtWidgets.QApplication.translate("MainWindow", "Options", None, -1))
        self.menuSelect.setTitle(QtWidgets.QApplication.translate("MainWindow", "Select", None, -1))
        self.toolBar.setWindowTitle(QtWidgets.QApplication.translate("MainWindow", "toolBar", None, -1))
        self.uiACT_refresh.setText(QtWidgets.QApplication.translate("MainWindow", "Refresh", None, -1))
        self.uiACT_refresh.setToolTip(QtWidgets.QApplication.translate("MainWindow", "Refresh", None, -1))
        self.uiACT_refresh.setShortcut(QtWidgets.QApplication.translate("MainWindow", "F5", None, -1))
        self.uiACT_exit.setText(QtWidgets.QApplication.translate("MainWindow", "Exit", None, -1))
        self.uiACT_retarget.setText(QtWidgets.QApplication.translate("MainWindow", "Retarget", None, -1))
        self.uiACT_copyMove.setText(QtWidgets.QApplication.translate("MainWindow", "Copy/Move", None, -1))
        self.uiACT_searchReplace.setText(QtWidgets.QApplication.translate("MainWindow", "Search and Replace", None, -1))
        self.uiACT_copyFullPath.setText(QtWidgets.QApplication.translate("MainWindow", "Copy Full Path", None, -1))
        self.uiACT_copyFilename.setText(QtWidgets.QApplication.translate("MainWindow", "Copy Filename", None, -1))
        self.uiACT_selectAssigned.setText(QtWidgets.QApplication.translate("MainWindow", "Select Assigned", None, -1))
        self.uiACT_collapseRepetitions.setText(QtWidgets.QApplication.translate("MainWindow", "Collapse Repetitions", None, -1))
        self.uiACT_selectAll.setText(QtWidgets.QApplication.translate("MainWindow", "Select All", None, -1))
        self.uiACT_selectNone.setText(QtWidgets.QApplication.translate("MainWindow", "Select None", None, -1))
        self.uiACT_selectInvert.setText(QtWidgets.QApplication.translate("MainWindow", "Select Invert", None, -1))
        self.uiACT_selectTextureNode.setText(QtWidgets.QApplication.translate("MainWindow", "Select Texture Node", None, -1))
        self.uiACT_selectNothing.setText(QtWidgets.QApplication.translate("MainWindow", "Select Nothing", None, -1))
        self.uiACT_copy.setText(QtWidgets.QApplication.translate("MainWindow", "Copy", None, -1))
        self.uiACT_paste.setText(QtWidgets.QApplication.translate("MainWindow", "Paste", None, -1))
        self.uiACT_analyzeSelection.setText(QtWidgets.QApplication.translate("MainWindow", "Analyze Selection", None, -1))
        self.uiACT_deleteUnusedShadingNodes.setText(QtWidgets.QApplication.translate("MainWindow", "Delete Unused Shading Nodes", None, -1))

import resources_rc2
