# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'main_window_ui.ui'
##
## Created by: Qt User Interface Compiler version 5.15.2
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide2.QtCore import *
from PySide2.QtGui import *
from PySide2.QtWidgets import *

from  . import resources_rc2

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(800, 610)
        icon = QIcon()
        icon.addFile(u":/icons/appIcon.png", QSize(), QIcon.Normal, QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.uiACT_refresh = QAction(MainWindow)
        self.uiACT_refresh.setObjectName(u"uiACT_refresh")
        icon1 = QIcon()
        icon1.addFile(u":/icons/refresh.png", QSize(), QIcon.Normal, QIcon.Off)
        self.uiACT_refresh.setIcon(icon1)
        self.uiACT_exit = QAction(MainWindow)
        self.uiACT_exit.setObjectName(u"uiACT_exit")
        icon2 = QIcon()
        icon2.addFile(u":/icons/exit.png", QSize(), QIcon.Normal, QIcon.Off)
        self.uiACT_exit.setIcon(icon2)
        self.uiACT_retarget = QAction(MainWindow)
        self.uiACT_retarget.setObjectName(u"uiACT_retarget")
        icon3 = QIcon()
        icon3.addFile(u":/icons/retarget.png", QSize(), QIcon.Normal, QIcon.Off)
        self.uiACT_retarget.setIcon(icon3)
        self.uiACT_copyMove = QAction(MainWindow)
        self.uiACT_copyMove.setObjectName(u"uiACT_copyMove")
        icon4 = QIcon()
        icon4.addFile(u":/icons/copy_move.png", QSize(), QIcon.Normal, QIcon.Off)
        self.uiACT_copyMove.setIcon(icon4)
        self.uiACT_searchReplace = QAction(MainWindow)
        self.uiACT_searchReplace.setObjectName(u"uiACT_searchReplace")
        icon5 = QIcon()
        icon5.addFile(u":/icons/replace.png", QSize(), QIcon.Normal, QIcon.Off)
        self.uiACT_searchReplace.setIcon(icon5)
        self.uiACT_copyFullPath = QAction(MainWindow)
        self.uiACT_copyFullPath.setObjectName(u"uiACT_copyFullPath")
        icon6 = QIcon()
        icon6.addFile(u":/icons/copy1.png", QSize(), QIcon.Normal, QIcon.Off)
        self.uiACT_copyFullPath.setIcon(icon6)
        self.uiACT_copyFilename = QAction(MainWindow)
        self.uiACT_copyFilename.setObjectName(u"uiACT_copyFilename")
        icon7 = QIcon()
        icon7.addFile(u":/icons/copy2.png", QSize(), QIcon.Normal, QIcon.Off)
        self.uiACT_copyFilename.setIcon(icon7)
        self.uiACT_selectAssigned = QAction(MainWindow)
        self.uiACT_selectAssigned.setObjectName(u"uiACT_selectAssigned")
        self.uiACT_selectAssigned.setCheckable(True)
        self.uiACT_collapseRepetitions = QAction(MainWindow)
        self.uiACT_collapseRepetitions.setObjectName(u"uiACT_collapseRepetitions")
        self.uiACT_collapseRepetitions.setCheckable(True)
        icon8 = QIcon()
        icon8.addFile(u":/icons/collapse.png", QSize(), QIcon.Normal, QIcon.Off)
        self.uiACT_collapseRepetitions.setIcon(icon8)
        self.uiACT_selectAll = QAction(MainWindow)
        self.uiACT_selectAll.setObjectName(u"uiACT_selectAll")
        self.uiACT_selectNone = QAction(MainWindow)
        self.uiACT_selectNone.setObjectName(u"uiACT_selectNone")
        self.uiACT_selectInvert = QAction(MainWindow)
        self.uiACT_selectInvert.setObjectName(u"uiACT_selectInvert")
        self.uiACT_selectTextureNode = QAction(MainWindow)
        self.uiACT_selectTextureNode.setObjectName(u"uiACT_selectTextureNode")
        self.uiACT_selectTextureNode.setCheckable(True)
        self.uiACT_selectNothing = QAction(MainWindow)
        self.uiACT_selectNothing.setObjectName(u"uiACT_selectNothing")
        self.uiACT_selectNothing.setCheckable(True)
        self.uiACT_copy = QAction(MainWindow)
        self.uiACT_copy.setObjectName(u"uiACT_copy")
        icon9 = QIcon()
        icon9.addFile(u":/icons/copy.png", QSize(), QIcon.Normal, QIcon.Off)
        self.uiACT_copy.setIcon(icon9)
        self.uiACT_paste = QAction(MainWindow)
        self.uiACT_paste.setObjectName(u"uiACT_paste")
        icon10 = QIcon()
        icon10.addFile(u":/icons/paste.png", QSize(), QIcon.Normal, QIcon.Off)
        self.uiACT_paste.setIcon(icon10)
        self.uiACT_analyzeSelection = QAction(MainWindow)
        self.uiACT_analyzeSelection.setObjectName(u"uiACT_analyzeSelection")
        self.uiACT_analyzeSelection.setCheckable(True)
        icon11 = QIcon()
        icon11.addFile(u":/icons/lock_to_selection.png", QSize(), QIcon.Normal, QIcon.Off)
        self.uiACT_analyzeSelection.setIcon(icon11)
        self.uiACT_deleteUnusedShadingNodes = QAction(MainWindow)
        self.uiACT_deleteUnusedShadingNodes.setObjectName(u"uiACT_deleteUnusedShadingNodes")
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.verticalLayout = QVBoxLayout(self.centralwidget)
        self.verticalLayout.setSpacing(4)
        self.verticalLayout.setObjectName(u"verticalLayout")
        self.verticalLayout.setContentsMargins(6, 6, 6, 6)
        self.horizontalLayout = QHBoxLayout()
        self.horizontalLayout.setObjectName(u"horizontalLayout")
        self.uiBTN_filter = QToolButton(self.centralwidget)
        self.uiBTN_filter.setObjectName(u"uiBTN_filter")
        self.uiBTN_filter.setMinimumSize(QSize(24, 24))
        self.uiBTN_filter.setMaximumSize(QSize(24, 24))
        icon12 = QIcon()
        icon12.addFile(u":/icons/filter_disabled.png", QSize(), QIcon.Normal, QIcon.Off)
        icon12.addFile(u":/icons/filter_active.png", QSize(), QIcon.Normal, QIcon.On)
        self.uiBTN_filter.setIcon(icon12)
        self.uiBTN_filter.setIconSize(QSize(18, 18))
        self.uiBTN_filter.setCheckable(True)

        self.horizontalLayout.addWidget(self.uiBTN_filter)

        self.uiLED_filter = QLineEdit(self.centralwidget)
        self.uiLED_filter.setObjectName(u"uiLED_filter")
        self.uiLED_filter.setMinimumSize(QSize(0, 24))

        self.horizontalLayout.addWidget(self.uiLED_filter)


        self.verticalLayout.addLayout(self.horizontalLayout)

        self.uiTBL_textures = QTableView(self.centralwidget)
        self.uiTBL_textures.setObjectName(u"uiTBL_textures")
        self.uiTBL_textures.setContextMenuPolicy(Qt.ActionsContextMenu)
        self.uiTBL_textures.setEditTriggers(QAbstractItemView.DoubleClicked)
        self.uiTBL_textures.setAlternatingRowColors(True)
        self.uiTBL_textures.setSelectionBehavior(QAbstractItemView.SelectRows)
        self.uiTBL_textures.setTextElideMode(Qt.ElideLeft)
        self.uiTBL_textures.setHorizontalScrollMode(QAbstractItemView.ScrollPerPixel)
        self.uiTBL_textures.setShowGrid(False)
        self.uiTBL_textures.setSortingEnabled(True)
        self.uiTBL_textures.horizontalHeader().setProperty("showSortIndicator", True)
        self.uiTBL_textures.horizontalHeader().setStretchLastSection(True)
        self.uiTBL_textures.verticalHeader().setVisible(False)
        self.uiTBL_textures.verticalHeader().setMinimumSectionSize(15)
        self.uiTBL_textures.verticalHeader().setDefaultSectionSize(15)

        self.verticalLayout.addWidget(self.uiTBL_textures)

        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QMenuBar(MainWindow)
        self.menubar.setObjectName(u"menubar")
        self.menubar.setGeometry(QRect(0, 0, 800, 21))
        self.menuFile = QMenu(self.menubar)
        self.menuFile.setObjectName(u"menuFile")
        self.menuActions = QMenu(self.menubar)
        self.menuActions.setObjectName(u"menuActions")
        self.menuEdit = QMenu(self.menubar)
        self.menuEdit.setObjectName(u"menuEdit")
        self.menuOptions = QMenu(self.menubar)
        self.menuOptions.setObjectName(u"menuOptions")
        self.menuSelect = QMenu(self.menubar)
        self.menuSelect.setObjectName(u"menuSelect")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QStatusBar(MainWindow)
        self.statusbar.setObjectName(u"statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.toolBar = QToolBar(MainWindow)
        self.toolBar.setObjectName(u"toolBar")
        self.toolBar.setMovable(False)
        self.toolBar.setIconSize(QSize(24, 24))
        self.toolBar.setFloatable(False)
        MainWindow.addToolBar(Qt.TopToolBarArea, self.toolBar)
        QWidget.setTabOrder(self.uiTBL_textures, self.uiLED_filter)
        QWidget.setTabOrder(self.uiLED_filter, self.uiBTN_filter)

        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuEdit.menuAction())
        self.menubar.addAction(self.menuSelect.menuAction())
        self.menubar.addAction(self.menuActions.menuAction())
        self.menubar.addAction(self.menuOptions.menuAction())
        self.menuFile.addAction(self.uiACT_refresh)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.uiACT_exit)
        self.menuActions.addAction(self.uiACT_deleteUnusedShadingNodes)
        self.menuActions.addSeparator()
        self.menuActions.addAction(self.uiACT_copyMove)
        self.menuActions.addAction(self.uiACT_retarget)
        self.menuActions.addAction(self.uiACT_searchReplace)
        self.menuEdit.addAction(self.uiACT_copy)
        self.menuEdit.addAction(self.uiACT_paste)
        self.menuEdit.addSeparator()
        self.menuEdit.addAction(self.uiACT_copyFullPath)
        self.menuEdit.addAction(self.uiACT_copyFilename)
        self.menuOptions.addAction(self.uiACT_collapseRepetitions)
        self.menuOptions.addAction(self.uiACT_analyzeSelection)
        self.menuOptions.addSeparator()
        self.menuOptions.addAction(self.uiACT_selectNothing)
        self.menuOptions.addAction(self.uiACT_selectAssigned)
        self.menuOptions.addAction(self.uiACT_selectTextureNode)
        self.menuSelect.addAction(self.uiACT_selectAll)
        self.menuSelect.addAction(self.uiACT_selectInvert)
        self.menuSelect.addAction(self.uiACT_selectNone)
        self.toolBar.addAction(self.uiACT_refresh)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.uiACT_analyzeSelection)
        self.toolBar.addAction(self.uiACT_collapseRepetitions)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.uiACT_copyFullPath)
        self.toolBar.addAction(self.uiACT_copyFilename)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.uiACT_copy)
        self.toolBar.addAction(self.uiACT_paste)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.uiACT_copyMove)
        self.toolBar.addAction(self.uiACT_retarget)
        self.toolBar.addAction(self.uiACT_searchReplace)

        self.retranslateUi(MainWindow)
        self.uiACT_exit.triggered.connect(MainWindow.close)
        self.uiACT_refresh.triggered.connect(MainWindow.onRefreshTriggered)
        self.uiACT_copyFullPath.triggered.connect(MainWindow.onCopyFullPathTriggered)
        self.uiACT_copyFilename.triggered.connect(MainWindow.onCopyFilenameTriggered)
        self.uiACT_copyMove.triggered.connect(MainWindow.onCopyMoveTriggered)
        self.uiACT_retarget.triggered.connect(MainWindow.onRetargetTriggered)
        self.uiACT_searchReplace.triggered.connect(MainWindow.onSearchReplaceTriggered)
        self.uiLED_filter.textChanged.connect(MainWindow.onFilterTextChanged)
        self.uiBTN_filter.toggled.connect(MainWindow.onFilterButtonToggled)
        self.uiACT_selectAll.triggered.connect(MainWindow.onSelectAllTriggered)
        self.uiACT_selectInvert.triggered.connect(MainWindow.onSelectInvertTriggered)
        self.uiACT_selectNone.triggered.connect(MainWindow.onSelectNoneTriggered)
        self.uiACT_collapseRepetitions.toggled.connect(MainWindow.onCollapseRepetitionsToggled)
        self.uiACT_selectTextureNode.toggled.connect(MainWindow.onChangeSelectionBehaviour)
        self.uiACT_selectAssigned.toggled.connect(MainWindow.onChangeSelectionBehaviour)
        self.uiACT_copy.triggered.connect(MainWindow.onCopyTriggered)
        self.uiACT_paste.triggered.connect(MainWindow.onPasteTriggered)
        self.uiACT_analyzeSelection.toggled.connect(MainWindow.onAnalyzeSelectionToggled)
        self.uiACT_deleteUnusedShadingNodes.triggered.connect(MainWindow.onDeleteUnusedShadingNodesTriggered)

        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"Texture Manager", None))
        self.uiACT_refresh.setText(QCoreApplication.translate("MainWindow", u"Refresh", None))
#if QT_CONFIG(tooltip)
        self.uiACT_refresh.setToolTip(QCoreApplication.translate("MainWindow", u"Refresh", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(shortcut)
        self.uiACT_refresh.setShortcut(QCoreApplication.translate("MainWindow", u"F5", None))
#endif // QT_CONFIG(shortcut)
        self.uiACT_exit.setText(QCoreApplication.translate("MainWindow", u"Exit", None))
        self.uiACT_retarget.setText(QCoreApplication.translate("MainWindow", u"Retarget", None))
        self.uiACT_copyMove.setText(QCoreApplication.translate("MainWindow", u"Copy/Move", None))
        self.uiACT_searchReplace.setText(QCoreApplication.translate("MainWindow", u"Search and Replace", None))
        self.uiACT_copyFullPath.setText(QCoreApplication.translate("MainWindow", u"Copy Full Path", None))
        self.uiACT_copyFilename.setText(QCoreApplication.translate("MainWindow", u"Copy Filename", None))
        self.uiACT_selectAssigned.setText(QCoreApplication.translate("MainWindow", u"Select Assigned", None))
        self.uiACT_collapseRepetitions.setText(QCoreApplication.translate("MainWindow", u"Collapse Repetitions", None))
        self.uiACT_selectAll.setText(QCoreApplication.translate("MainWindow", u"Select All", None))
        self.uiACT_selectNone.setText(QCoreApplication.translate("MainWindow", u"Select None", None))
        self.uiACT_selectInvert.setText(QCoreApplication.translate("MainWindow", u"Select Invert", None))
        self.uiACT_selectTextureNode.setText(QCoreApplication.translate("MainWindow", u"Select Texture Node", None))
        self.uiACT_selectNothing.setText(QCoreApplication.translate("MainWindow", u"Select Nothing", None))
        self.uiACT_copy.setText(QCoreApplication.translate("MainWindow", u"Copy", None))
        self.uiACT_paste.setText(QCoreApplication.translate("MainWindow", u"Paste", None))
        self.uiACT_analyzeSelection.setText(QCoreApplication.translate("MainWindow", u"Analyze Selection", None))
        self.uiACT_deleteUnusedShadingNodes.setText(QCoreApplication.translate("MainWindow", u"Delete Unused Shading Nodes", None))
        self.uiBTN_filter.setText(QCoreApplication.translate("MainWindow", u"...", None))
        self.menuFile.setTitle(QCoreApplication.translate("MainWindow", u"File", None))
        self.menuActions.setTitle(QCoreApplication.translate("MainWindow", u"Actions", None))
        self.menuEdit.setTitle(QCoreApplication.translate("MainWindow", u"Edit", None))
        self.menuOptions.setTitle(QCoreApplication.translate("MainWindow", u"Options", None))
        self.menuSelect.setTitle(QCoreApplication.translate("MainWindow", u"Select", None))
        self.toolBar.setWindowTitle(QCoreApplication.translate("MainWindow", u"toolBar", None))
    # retranslateUi

