# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainWindowUI.ui'
#
# Created: Mon Jul 21 21:17:00 2014
#      by: pyside-uic 0.2.15 running on PySide 1.2.2
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(881, 636)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/fx_search_search.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.centralwidget)
        self.verticalLayout_5.setContentsMargins(6, 6, 6, 6)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.frame = QtGui.QFrame(self.centralwidget)
        self.frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtGui.QFrame.Sunken)
        self.frame.setObjectName("frame")
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.frame)
        self.verticalLayout_4.setSpacing(0)
        self.verticalLayout_4.setContentsMargins(4, 8, 4, 8)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.verticalLayout_3 = QtGui.QVBoxLayout()
        self.verticalLayout_3.setSpacing(10)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_8 = QtGui.QHBoxLayout()
        self.horizontalLayout_8.setSpacing(2)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        spacerItem = QtGui.QSpacerItem(4, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem)
        self.ui_LED_search = QtGui.QLineEdit(self.frame)
        self.ui_LED_search.setObjectName("ui_LED_search")
        self.horizontalLayout_8.addWidget(self.ui_LED_search)
        spacerItem1 = QtGui.QSpacerItem(2, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem1)
        self.ui_BTN_search = QtGui.QPushButton(self.frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ui_BTN_search.sizePolicy().hasHeightForWidth())
        self.ui_BTN_search.setSizePolicy(sizePolicy)
        self.ui_BTN_search.setMaximumSize(QtCore.QSize(24, 24))
        self.ui_BTN_search.setText("")
        self.ui_BTN_search.setIcon(icon)
        self.ui_BTN_search.setIconSize(QtCore.QSize(22, 22))
        self.ui_BTN_search.setObjectName("ui_BTN_search")
        self.horizontalLayout_8.addWidget(self.ui_BTN_search)
        spacerItem2 = QtGui.QSpacerItem(4, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem2)
        self.ui_BTN_soCaseSensitive = QtGui.QPushButton(self.frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ui_BTN_soCaseSensitive.sizePolicy().hasHeightForWidth())
        self.ui_BTN_soCaseSensitive.setSizePolicy(sizePolicy)
        self.ui_BTN_soCaseSensitive.setMaximumSize(QtCore.QSize(24, 24))
        self.ui_BTN_soCaseSensitive.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/fx_search_case.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.ui_BTN_soCaseSensitive.setIcon(icon1)
        self.ui_BTN_soCaseSensitive.setIconSize(QtCore.QSize(20, 20))
        self.ui_BTN_soCaseSensitive.setCheckable(True)
        self.ui_BTN_soCaseSensitive.setFlat(True)
        self.ui_BTN_soCaseSensitive.setObjectName("ui_BTN_soCaseSensitive")
        self.horizontalLayout_8.addWidget(self.ui_BTN_soCaseSensitive)
        self.ui_BTN_soRegex = QtGui.QPushButton(self.frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ui_BTN_soRegex.sizePolicy().hasHeightForWidth())
        self.ui_BTN_soRegex.setSizePolicy(sizePolicy)
        self.ui_BTN_soRegex.setMaximumSize(QtCore.QSize(24, 24))
        self.ui_BTN_soRegex.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icons/fx_search_regex.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.ui_BTN_soRegex.setIcon(icon2)
        self.ui_BTN_soRegex.setIconSize(QtCore.QSize(22, 22))
        self.ui_BTN_soRegex.setCheckable(True)
        self.ui_BTN_soRegex.setFlat(True)
        self.ui_BTN_soRegex.setObjectName("ui_BTN_soRegex")
        self.horizontalLayout_8.addWidget(self.ui_BTN_soRegex)
        self.ui_BTN_soSelectFound = QtGui.QPushButton(self.frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ui_BTN_soSelectFound.sizePolicy().hasHeightForWidth())
        self.ui_BTN_soSelectFound.setSizePolicy(sizePolicy)
        self.ui_BTN_soSelectFound.setMaximumSize(QtCore.QSize(24, 24))
        self.ui_BTN_soSelectFound.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/icons/fx_search_select.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.ui_BTN_soSelectFound.setIcon(icon3)
        self.ui_BTN_soSelectFound.setIconSize(QtCore.QSize(20, 20))
        self.ui_BTN_soSelectFound.setCheckable(True)
        self.ui_BTN_soSelectFound.setFlat(True)
        self.ui_BTN_soSelectFound.setObjectName("ui_BTN_soSelectFound")
        self.horizontalLayout_8.addWidget(self.ui_BTN_soSelectFound)
        self.ui_BTN_soIncludeShapes = QtGui.QPushButton(self.frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ui_BTN_soIncludeShapes.sizePolicy().hasHeightForWidth())
        self.ui_BTN_soIncludeShapes.setSizePolicy(sizePolicy)
        self.ui_BTN_soIncludeShapes.setMaximumSize(QtCore.QSize(24, 24))
        self.ui_BTN_soIncludeShapes.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/icons/fx_search_shape.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.ui_BTN_soIncludeShapes.setIcon(icon4)
        self.ui_BTN_soIncludeShapes.setIconSize(QtCore.QSize(20, 20))
        self.ui_BTN_soIncludeShapes.setCheckable(True)
        self.ui_BTN_soIncludeShapes.setFlat(True)
        self.ui_BTN_soIncludeShapes.setObjectName("ui_BTN_soIncludeShapes")
        self.horizontalLayout_8.addWidget(self.ui_BTN_soIncludeShapes)
        self.ui_BTN_soSearchSelected = QtGui.QPushButton(self.frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ui_BTN_soSearchSelected.sizePolicy().hasHeightForWidth())
        self.ui_BTN_soSearchSelected.setSizePolicy(sizePolicy)
        self.ui_BTN_soSearchSelected.setMaximumSize(QtCore.QSize(24, 24))
        self.ui_BTN_soSearchSelected.setText("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/icons/fx_search_inSelected.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.ui_BTN_soSearchSelected.setIcon(icon5)
        self.ui_BTN_soSearchSelected.setIconSize(QtCore.QSize(20, 20))
        self.ui_BTN_soSearchSelected.setCheckable(True)
        self.ui_BTN_soSearchSelected.setFlat(True)
        self.ui_BTN_soSearchSelected.setObjectName("ui_BTN_soSearchSelected")
        self.horizontalLayout_8.addWidget(self.ui_BTN_soSearchSelected)
        self.verticalLayout_3.addLayout(self.horizontalLayout_8)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setSpacing(6)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.groupBox = QtGui.QGroupBox(self.frame)
        self.groupBox.setObjectName("groupBox")
        self.horizontalLayout_5 = QtGui.QHBoxLayout(self.groupBox)
        self.horizontalLayout_5.setSpacing(0)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.ui_STK_results = QtGui.QStackedWidget(self.groupBox)
        self.ui_STK_results.setObjectName("ui_STK_results")
        self.ui_STKPG_status = QtGui.QWidget()
        self.ui_STKPG_status.setObjectName("ui_STKPG_status")
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.ui_STKPG_status)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.ui_TXT_status = QtGui.QLabel(self.ui_STKPG_status)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(24)
        self.ui_TXT_status.setFont(font)
        self.ui_TXT_status.setAlignment(QtCore.Qt.AlignCenter)
        self.ui_TXT_status.setObjectName("ui_TXT_status")
        self.horizontalLayout_2.addWidget(self.ui_TXT_status)
        self.ui_STK_results.addWidget(self.ui_STKPG_status)
        self.ui_STKPG_results = QtGui.QWidget()
        self.ui_STKPG_results.setObjectName("ui_STKPG_results")
        self.horizontalLayout_4 = QtGui.QHBoxLayout(self.ui_STKPG_results)
        self.horizontalLayout_4.setContentsMargins(4, 4, 4, 4)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.ui_TAB_results = QtGui.QTabWidget(self.ui_STKPG_results)
        self.ui_TAB_results.setObjectName("ui_TAB_results")
        self.horizontalLayout_4.addWidget(self.ui_TAB_results)
        self.ui_STK_results.addWidget(self.ui_STKPG_results)
        self.horizontalLayout_5.addWidget(self.ui_STK_results)
        self.horizontalLayout.addWidget(self.groupBox)
        self.groupBox_2 = QtGui.QGroupBox(self.frame)
        self.groupBox_2.setMinimumSize(QtCore.QSize(140, 0))
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_2.setSpacing(4)
        self.verticalLayout_2.setContentsMargins(6, 2, 6, 6)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.ui_BTN_catAllOn = QtGui.QPushButton(self.groupBox_2)
        self.ui_BTN_catAllOn.setObjectName("ui_BTN_catAllOn")
        self.horizontalLayout_6.addWidget(self.ui_BTN_catAllOn)
        self.ui_BTN_catAllOff = QtGui.QPushButton(self.groupBox_2)
        self.ui_BTN_catAllOff.setObjectName("ui_BTN_catAllOff")
        self.horizontalLayout_6.addWidget(self.ui_BTN_catAllOff)
        self.verticalLayout_2.addLayout(self.horizontalLayout_6)
        self.line = QtGui.QFrame(self.groupBox_2)
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout_2.addWidget(self.line)
        self.ui_LAY_catButtons = QtGui.QVBoxLayout()
        self.ui_LAY_catButtons.setSpacing(2)
        self.ui_LAY_catButtons.setObjectName("ui_LAY_catButtons")
        self.verticalLayout_2.addLayout(self.ui_LAY_catButtons)
        self.verticalLayout_2.setStretch(2, 1)
        self.horizontalLayout.addWidget(self.groupBox_2)
        self.verticalLayout_3.addLayout(self.horizontalLayout)
        self.verticalLayout_4.addLayout(self.verticalLayout_3)
        self.verticalLayout_5.addWidget(self.frame)
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        spacerItem3 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem3)
        self.ui_BTN_close = QtGui.QPushButton(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ui_BTN_close.sizePolicy().hasHeightForWidth())
        self.ui_BTN_close.setSizePolicy(sizePolicy)
        self.ui_BTN_close.setMinimumSize(QtCore.QSize(100, 30))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setWeight(75)
        font.setBold(True)
        self.ui_BTN_close.setFont(font)
        self.ui_BTN_close.setObjectName("ui_BTN_close")
        self.horizontalLayout_7.addWidget(self.ui_BTN_close)
        self.verticalLayout_5.addLayout(self.horizontalLayout_7)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menuBar = QtGui.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 881, 21))
        self.menuBar.setObjectName("menuBar")
        self.menuSelect = QtGui.QMenu(self.menuBar)
        self.menuSelect.setObjectName("menuSelect")
        self.menuOptions = QtGui.QMenu(self.menuBar)
        self.menuOptions.setObjectName("menuOptions")
        self.menuHelp = QtGui.QMenu(self.menuBar)
        self.menuHelp.setObjectName("menuHelp")
        self.menuEdit = QtGui.QMenu(self.menuBar)
        self.menuEdit.setObjectName("menuEdit")
        MainWindow.setMenuBar(self.menuBar)
        self.ui_ACT_selectAll = QtGui.QAction(MainWindow)
        self.ui_ACT_selectAll.setObjectName("ui_ACT_selectAll")
        self.ui_ACT_deselectAll = QtGui.QAction(MainWindow)
        self.ui_ACT_deselectAll.setObjectName("ui_ACT_deselectAll")
        self.ui_ACT_useAllTabs = QtGui.QAction(MainWindow)
        self.ui_ACT_useAllTabs.setCheckable(True)
        self.ui_ACT_useAllTabs.setObjectName("ui_ACT_useAllTabs")
        self.ui_ACT_copyFullNamesToClipboard = QtGui.QAction(MainWindow)
        self.ui_ACT_copyFullNamesToClipboard.setObjectName("ui_ACT_copyFullNamesToClipboard")
        self.ui_ACT_copyShortNamesToClipboard = QtGui.QAction(MainWindow)
        self.ui_ACT_copyShortNamesToClipboard.setObjectName("ui_ACT_copyShortNamesToClipboard")
        self.ui_ACT_showHelp = QtGui.QAction(MainWindow)
        self.ui_ACT_showHelp.setObjectName("ui_ACT_showHelp")
        self.menuSelect.addAction(self.ui_ACT_selectAll)
        self.menuSelect.addAction(self.ui_ACT_deselectAll)
        self.menuSelect.addSeparator()
        self.menuOptions.addAction(self.ui_ACT_useAllTabs)
        self.menuHelp.addAction(self.ui_ACT_showHelp)
        self.menuEdit.addAction(self.ui_ACT_copyFullNamesToClipboard)
        self.menuEdit.addAction(self.ui_ACT_copyShortNamesToClipboard)
        self.menuBar.addAction(self.menuEdit.menuAction())
        self.menuBar.addAction(self.menuSelect.menuAction())
        self.menuBar.addAction(self.menuOptions.menuAction())
        self.menuBar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        self.ui_STK_results.setCurrentIndex(1)
        self.ui_TAB_results.setCurrentIndex(-1)
        QtCore.QObject.connect(self.ui_BTN_catAllOn, QtCore.SIGNAL("clicked()"), MainWindow.ui_onCatOnOffClicked)
        QtCore.QObject.connect(self.ui_BTN_catAllOff, QtCore.SIGNAL("clicked()"), MainWindow.ui_onCatOnOffClicked)
        QtCore.QObject.connect(self.ui_BTN_close, QtCore.SIGNAL("clicked()"), MainWindow.ui_onCloseClicked)
        QtCore.QObject.connect(self.ui_BTN_search, QtCore.SIGNAL("clicked()"), MainWindow.ui_onSearchClicked)
        QtCore.QObject.connect(self.ui_LED_search, QtCore.SIGNAL("returnPressed()"), MainWindow.ui_onSearchClicked)
        QtCore.QObject.connect(self.ui_TAB_results, QtCore.SIGNAL("currentChanged(int)"), MainWindow.ui_onResultTabChanged)
        QtCore.QObject.connect(self.ui_ACT_useAllTabs, QtCore.SIGNAL("changed()"), MainWindow.ui_onResultTabChanged)
        QtCore.QObject.connect(self.ui_ACT_showHelp, QtCore.SIGNAL("triggered()"), MainWindow.ui_onShowHelpClicked)
        QtCore.QObject.connect(self.ui_ACT_selectAll, QtCore.SIGNAL("triggered()"), MainWindow.ui_onSelectAllClicked)
        QtCore.QObject.connect(self.ui_ACT_deselectAll, QtCore.SIGNAL("triggered()"), MainWindow.ui_onDeselectAllClicked)
        QtCore.QObject.connect(self.ui_ACT_copyFullNamesToClipboard, QtCore.SIGNAL("triggered()"), MainWindow.ui_onCopyFullNameClicked)
        QtCore.QObject.connect(self.ui_ACT_copyShortNamesToClipboard, QtCore.SIGNAL("triggered()"), MainWindow.ui_onCopyShortNameClicked)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "Search", None, QtGui.QApplication.UnicodeUTF8))
        self.ui_BTN_soCaseSensitive.setToolTip(QtGui.QApplication.translate("MainWindow", "Case Sensitive", None, QtGui.QApplication.UnicodeUTF8))
        self.ui_BTN_soRegex.setToolTip(QtGui.QApplication.translate("MainWindow", "Search by Regular Expression", None, QtGui.QApplication.UnicodeUTF8))
        self.ui_BTN_soSelectFound.setToolTip(QtGui.QApplication.translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: nowrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:8pt;\">Select all Found Objects</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.ui_BTN_soIncludeShapes.setToolTip(QtGui.QApplication.translate("MainWindow", "Include Shapes in Search", None, QtGui.QApplication.UnicodeUTF8))
        self.ui_BTN_soSearchSelected.setToolTip(QtGui.QApplication.translate("MainWindow", "Search in Selected Objects", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setTitle(QtGui.QApplication.translate("MainWindow", "Search Results", None, QtGui.QApplication.UnicodeUTF8))
        self.ui_TXT_status.setText(QtGui.QApplication.translate("MainWindow", "searching...", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_2.setTitle(QtGui.QApplication.translate("MainWindow", "Search Categories", None, QtGui.QApplication.UnicodeUTF8))
        self.ui_BTN_catAllOn.setText(QtGui.QApplication.translate("MainWindow", "All On", None, QtGui.QApplication.UnicodeUTF8))
        self.ui_BTN_catAllOff.setText(QtGui.QApplication.translate("MainWindow", "All Off", None, QtGui.QApplication.UnicodeUTF8))
        self.ui_BTN_close.setText(QtGui.QApplication.translate("MainWindow", "Close", None, QtGui.QApplication.UnicodeUTF8))
        self.menuSelect.setTitle(QtGui.QApplication.translate("MainWindow", "Select", None, QtGui.QApplication.UnicodeUTF8))
        self.menuOptions.setTitle(QtGui.QApplication.translate("MainWindow", "Options", None, QtGui.QApplication.UnicodeUTF8))
        self.menuHelp.setTitle(QtGui.QApplication.translate("MainWindow", "Help", None, QtGui.QApplication.UnicodeUTF8))
        self.menuEdit.setTitle(QtGui.QApplication.translate("MainWindow", "Edit", None, QtGui.QApplication.UnicodeUTF8))
        self.ui_ACT_selectAll.setText(QtGui.QApplication.translate("MainWindow", "Select All", None, QtGui.QApplication.UnicodeUTF8))
        self.ui_ACT_selectAll.setToolTip(QtGui.QApplication.translate("MainWindow", "Select All", None, QtGui.QApplication.UnicodeUTF8))
        self.ui_ACT_deselectAll.setText(QtGui.QApplication.translate("MainWindow", "Deselect All", None, QtGui.QApplication.UnicodeUTF8))
        self.ui_ACT_deselectAll.setToolTip(QtGui.QApplication.translate("MainWindow", "Deselect All", None, QtGui.QApplication.UnicodeUTF8))
        self.ui_ACT_useAllTabs.setText(QtGui.QApplication.translate("MainWindow", "Use All Tabs", None, QtGui.QApplication.UnicodeUTF8))
        self.ui_ACT_useAllTabs.setToolTip(QtGui.QApplication.translate("MainWindow", "Use All Tabs", None, QtGui.QApplication.UnicodeUTF8))
        self.ui_ACT_copyFullNamesToClipboard.setText(QtGui.QApplication.translate("MainWindow", "Copy Full Names to Clipboard", None, QtGui.QApplication.UnicodeUTF8))
        self.ui_ACT_copyShortNamesToClipboard.setText(QtGui.QApplication.translate("MainWindow", "Copy Short Names to Clipboard", None, QtGui.QApplication.UnicodeUTF8))
        self.ui_ACT_showHelp.setText(QtGui.QApplication.translate("MainWindow", "Help on FX Search", None, QtGui.QApplication.UnicodeUTF8))
        self.ui_ACT_showHelp.setToolTip(QtGui.QApplication.translate("MainWindow", "Help on FX Search", None, QtGui.QApplication.UnicodeUTF8))

import resources_rc
