# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'CopyMoveDialogUI.ui'
#
# Created: Thu Jan 15 21:22:59 2015
#      by: pyside-uic 0.2.15 running on PySide 1.2.2
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(813, 350)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Dialog.sizePolicy().hasHeightForWidth())
        Dialog.setSizePolicy(sizePolicy)
        Dialog.setMaximumSize(QtCore.QSize(16777215, 350))
        self.verticalLayout_2 = QtGui.QVBoxLayout(Dialog)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.groupBox_2 = QtGui.QGroupBox(Dialog)
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout = QtGui.QVBoxLayout(self.groupBox_2)
        self.verticalLayout.setObjectName("verticalLayout")
        self.gridLayout_3 = QtGui.QGridLayout()
        self.gridLayout_3.setHorizontalSpacing(6)
        self.gridLayout_3.setVerticalSpacing(4)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.uiCHK_deleteSources = QtGui.QCheckBox(self.groupBox_2)
        self.uiCHK_deleteSources.setMinimumSize(QtCore.QSize(0, 20))
        self.uiCHK_deleteSources.setObjectName("uiCHK_deleteSources")
        self.gridLayout_3.addWidget(self.uiCHK_deleteSources, 1, 1, 1, 1)
        self.uiBTN_browse_4 = QtGui.QToolButton(self.groupBox_2)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/folder.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.uiBTN_browse_4.setIcon(icon)
        self.uiBTN_browse_4.setIconSize(QtCore.QSize(18, 18))
        self.uiBTN_browse_4.setObjectName("uiBTN_browse_4")
        self.gridLayout_3.addWidget(self.uiBTN_browse_4, 0, 2, 1, 1)
        self.uiLED_targetRoot = LineEditPath(self.groupBox_2)
        self.uiLED_targetRoot.setObjectName("uiLED_targetRoot")
        self.gridLayout_3.addWidget(self.uiLED_targetRoot, 0, 1, 1, 1)
        self.label_10 = QtGui.QLabel(self.groupBox_2)
        self.label_10.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_10.setObjectName("label_10")
        self.gridLayout_3.addWidget(self.label_10, 0, 0, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout_3)
        self.uiGRP_folderStructure = QtGui.QGroupBox(self.groupBox_2)
        self.uiGRP_folderStructure.setCheckable(True)
        self.uiGRP_folderStructure.setObjectName("uiGRP_folderStructure")
        self.gridLayout = QtGui.QGridLayout(self.uiGRP_folderStructure)
        self.gridLayout.setObjectName("gridLayout")
        self.uiLED_sourceRoot = LineEditPath(self.uiGRP_folderStructure)
        self.uiLED_sourceRoot.setObjectName("uiLED_sourceRoot")
        self.gridLayout.addWidget(self.uiLED_sourceRoot, 0, 1, 1, 1)
        self.uiBTN_browse_5 = QtGui.QToolButton(self.uiGRP_folderStructure)
        self.uiBTN_browse_5.setIcon(icon)
        self.uiBTN_browse_5.setIconSize(QtCore.QSize(18, 18))
        self.uiBTN_browse_5.setObjectName("uiBTN_browse_5")
        self.gridLayout.addWidget(self.uiBTN_browse_5, 0, 2, 1, 1)
        self.label_16 = QtGui.QLabel(self.uiGRP_folderStructure)
        self.label_16.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_16.setObjectName("label_16")
        self.gridLayout.addWidget(self.label_16, 0, 0, 1, 1)
        self.verticalLayout.addWidget(self.uiGRP_folderStructure)
        self.uiGRP_addTextures = QtGui.QGroupBox(self.groupBox_2)
        self.uiGRP_addTextures.setCheckable(True)
        self.uiGRP_addTextures.setObjectName("uiGRP_addTextures")
        self.gridLayout_2 = QtGui.QGridLayout(self.uiGRP_addTextures)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_22 = QtGui.QLabel(self.uiGRP_addTextures)
        self.label_22.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_22.setObjectName("label_22")
        self.gridLayout_2.addWidget(self.label_22, 0, 0, 1, 1)
        self.uiLED_texSuffixes = QtGui.QLineEdit(self.uiGRP_addTextures)
        self.uiLED_texSuffixes.setObjectName("uiLED_texSuffixes")
        self.gridLayout_2.addWidget(self.uiLED_texSuffixes, 0, 1, 1, 1)
        self.verticalLayout.addWidget(self.uiGRP_addTextures)
        self.verticalLayout_2.addWidget(self.groupBox_2)
        self.groupBox_3 = QtGui.QGroupBox(Dialog)
        self.groupBox_3.setObjectName("groupBox_3")
        self.horizontalLayout_4 = QtGui.QHBoxLayout(self.groupBox_3)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.uiCHK_retarget = QtGui.QCheckBox(self.groupBox_3)
        self.uiCHK_retarget.setMinimumSize(QtCore.QSize(0, 20))
        self.uiCHK_retarget.setObjectName("uiCHK_retarget")
        self.horizontalLayout_4.addWidget(self.uiCHK_retarget)
        self.uiCHK_forceRetarget = QtGui.QCheckBox(self.groupBox_3)
        self.uiCHK_forceRetarget.setMinimumSize(QtCore.QSize(0, 20))
        self.uiCHK_forceRetarget.setObjectName("uiCHK_forceRetarget")
        self.horizontalLayout_4.addWidget(self.uiCHK_forceRetarget)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem)
        self.verticalLayout_2.addWidget(self.groupBox_3)
        spacerItem1 = QtGui.QSpacerItem(20, 30, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem1)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.uiLBL_status = QtGui.QLabel(Dialog)
        self.uiLBL_status.setStyleSheet("QLabel {color : red}")
        self.uiLBL_status.setText("")
        self.uiLBL_status.setObjectName("uiLBL_status")
        self.horizontalLayout_2.addWidget(self.uiLBL_status)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem2)
        self.uiBTN_ok = QtGui.QPushButton(Dialog)
        self.uiBTN_ok.setObjectName("uiBTN_ok")
        self.horizontalLayout_2.addWidget(self.uiBTN_ok)
        self.uiBTN_cancel = QtGui.QPushButton(Dialog)
        self.uiBTN_cancel.setObjectName("uiBTN_cancel")
        self.horizontalLayout_2.addWidget(self.uiBTN_cancel)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)

        self.retranslateUi(Dialog)
        QtCore.QObject.connect(self.uiBTN_cancel, QtCore.SIGNAL("clicked()"), Dialog.reject)
        QtCore.QObject.connect(Dialog, QtCore.SIGNAL("finished(int)"), Dialog.onDialogFinished)
        QtCore.QObject.connect(self.uiBTN_ok, QtCore.SIGNAL("clicked()"), Dialog.onOkClicked)
        QtCore.QMetaObject.connectSlotsByName(Dialog)
        Dialog.setTabOrder(self.uiBTN_cancel, self.uiBTN_ok)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(QtGui.QApplication.translate("Dialog", "Copy and Move", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_2.setTitle(QtGui.QApplication.translate("Dialog", "Parameters", None, QtGui.QApplication.UnicodeUTF8))
        self.uiCHK_deleteSources.setText(QtGui.QApplication.translate("Dialog", "Delete sources", None, QtGui.QApplication.UnicodeUTF8))
        self.uiBTN_browse_4.setText(QtGui.QApplication.translate("Dialog", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.uiBTN_browse_4.setShortcut(QtGui.QApplication.translate("Dialog", "Ctrl+S, Ctrl+R", None, QtGui.QApplication.UnicodeUTF8))
        self.label_10.setText(QtGui.QApplication.translate("Dialog", "Copy to:", None, QtGui.QApplication.UnicodeUTF8))
        self.uiGRP_folderStructure.setTitle(QtGui.QApplication.translate("Dialog", "Copy folder structure", None, QtGui.QApplication.UnicodeUTF8))
        self.uiBTN_browse_5.setText(QtGui.QApplication.translate("Dialog", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.uiBTN_browse_5.setShortcut(QtGui.QApplication.translate("Dialog", "Ctrl+S, Ctrl+R", None, QtGui.QApplication.UnicodeUTF8))
        self.label_16.setText(QtGui.QApplication.translate("Dialog", "Original folder root:", None, QtGui.QApplication.UnicodeUTF8))
        self.uiGRP_addTextures.setTitle(QtGui.QApplication.translate("Dialog", "Copy additional textures", None, QtGui.QApplication.UnicodeUTF8))
        self.label_22.setText(QtGui.QApplication.translate("Dialog", "Texture suffixes:", None, QtGui.QApplication.UnicodeUTF8))
        self.uiLED_texSuffixes.setText(QtGui.QApplication.translate("Dialog", "_nm, _spec, _hdetm, _em", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_3.setTitle(QtGui.QApplication.translate("Dialog", "Post Processing", None, QtGui.QApplication.UnicodeUTF8))
        self.uiCHK_retarget.setText(QtGui.QApplication.translate("Dialog", "Retarget", None, QtGui.QApplication.UnicodeUTF8))
        self.uiCHK_forceRetarget.setText(QtGui.QApplication.translate("Dialog", "Force Retarget", None, QtGui.QApplication.UnicodeUTF8))
        self.uiBTN_ok.setText(QtGui.QApplication.translate("Dialog", "OK", None, QtGui.QApplication.UnicodeUTF8))
        self.uiBTN_cancel.setText(QtGui.QApplication.translate("Dialog", "Cancel", None, QtGui.QApplication.UnicodeUTF8))

from LineEditPath import LineEditPath
import resources_rc
