# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'RetargetDialogUI.ui'
#
# Created: Fri Jan 09 22:46:34 2015
#      by: pyside-uic 0.2.15 running on PySide 1.2.2
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(651, 146)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Dialog.sizePolicy().hasHeightForWidth())
        Dialog.setSizePolicy(sizePolicy)
        Dialog.setMaximumSize(QtCore.QSize(16777215, 200))
        self.verticalLayout = QtGui.QVBoxLayout(Dialog)
        self.verticalLayout.setContentsMargins(6, 6, 6, 6)
        self.verticalLayout.setObjectName("verticalLayout")
        self.groupBox = QtGui.QGroupBox(Dialog)
        self.groupBox.setObjectName("groupBox")
        self.horizontalLayout = QtGui.QHBoxLayout(self.groupBox)
        self.horizontalLayout.setContentsMargins(-1, 6, -1, 9)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setHorizontalSpacing(6)
        self.gridLayout.setVerticalSpacing(4)
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtGui.QLabel(self.groupBox)
        self.label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.uiLED_retargetRoot = QtGui.QLineEdit(self.groupBox)
        self.uiLED_retargetRoot.setObjectName("uiLED_retargetRoot")
        self.gridLayout.addWidget(self.uiLED_retargetRoot, 0, 1, 1, 1)
        self.label_2 = QtGui.QLabel(self.groupBox)
        self.label_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.uiCHK_forceRetarget = QtGui.QCheckBox(self.groupBox)
        self.uiCHK_forceRetarget.setMinimumSize(QtCore.QSize(0, 20))
        self.uiCHK_forceRetarget.setText("")
        self.uiCHK_forceRetarget.setObjectName("uiCHK_forceRetarget")
        self.gridLayout.addWidget(self.uiCHK_forceRetarget, 1, 1, 1, 1)
        self.uiBTN_browse = QtGui.QToolButton(self.groupBox)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/folder.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.uiBTN_browse.setIcon(icon)
        self.uiBTN_browse.setIconSize(QtCore.QSize(18, 18))
        self.uiBTN_browse.setObjectName("uiBTN_browse")
        self.gridLayout.addWidget(self.uiBTN_browse, 0, 2, 1, 1)
        self.horizontalLayout.addLayout(self.gridLayout)
        self.verticalLayout.addWidget(self.groupBox)
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.uiLBL_status = QtGui.QLabel(Dialog)
        self.uiLBL_status.setStyleSheet("QLabel {color : red}")
        self.uiLBL_status.setText("")
        self.uiLBL_status.setObjectName("uiLBL_status")
        self.horizontalLayout_2.addWidget(self.uiLBL_status)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.uiBTN_ok = QtGui.QPushButton(Dialog)
        self.uiBTN_ok.setObjectName("uiBTN_ok")
        self.horizontalLayout_2.addWidget(self.uiBTN_ok)
        self.uiBTN_cancel = QtGui.QPushButton(Dialog)
        self.uiBTN_cancel.setObjectName("uiBTN_cancel")
        self.horizontalLayout_2.addWidget(self.uiBTN_cancel)
        self.verticalLayout.addLayout(self.horizontalLayout_2)

        self.retranslateUi(Dialog)
        QtCore.QObject.connect(self.uiLED_retargetRoot, QtCore.SIGNAL("editingFinished()"), Dialog.onRetargetRootEditingFinished)
        QtCore.QObject.connect(self.uiBTN_ok, QtCore.SIGNAL("clicked()"), Dialog.accept)
        QtCore.QObject.connect(self.uiBTN_cancel, QtCore.SIGNAL("clicked()"), Dialog.reject)
        QtCore.QObject.connect(self.uiBTN_browse, QtCore.SIGNAL("clicked()"), Dialog.onBrowseClicked)
        QtCore.QObject.connect(Dialog, QtCore.SIGNAL("finished(int)"), Dialog.onDialogFinished)
        QtCore.QMetaObject.connectSlotsByName(Dialog)
        Dialog.setTabOrder(self.uiLED_retargetRoot, self.uiBTN_browse)
        Dialog.setTabOrder(self.uiBTN_browse, self.uiBTN_cancel)
        Dialog.setTabOrder(self.uiBTN_cancel, self.uiCHK_forceRetarget)
        Dialog.setTabOrder(self.uiCHK_forceRetarget, self.uiBTN_ok)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(QtGui.QApplication.translate("Dialog", "Retarget", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setTitle(QtGui.QApplication.translate("Dialog", "Parameters", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("Dialog", "Retarget to:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("Dialog", "Force retarget", None, QtGui.QApplication.UnicodeUTF8))
        self.uiBTN_browse.setText(QtGui.QApplication.translate("Dialog", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.uiBTN_browse.setShortcut(QtGui.QApplication.translate("Dialog", "Ctrl+S, Ctrl+R", None, QtGui.QApplication.UnicodeUTF8))
        self.uiBTN_ok.setText(QtGui.QApplication.translate("Dialog", "OK", None, QtGui.QApplication.UnicodeUTF8))
        self.uiBTN_cancel.setText(QtGui.QApplication.translate("Dialog", "Cancel", None, QtGui.QApplication.UnicodeUTF8))

import resources_rc
