import os
import maya.cmds as m

from fxpt.fx_utils.utils import pathToSlash


MAYA_VERSION = m.about(version=True)
TOOL_DIR = pathToSlash(os.path.dirname(__file__))
TOOLS_CFG = TOOL_DIR + '/tools_list.json'


UI_FRAME_WIDTH = 500
UI_FRAME_CENTER_OFFSET = -100
UI_ITEM_SIZE = 18
UI_LIST_SIZE_BOTTOM_MARGIN = 4
UI_MAX_RESULTS_HEIGHT = 300
UI_CONTENTS_MARGIN = 5
UI_SPACING = 5
UI_STATUS_LABEL_HEIGHT = 20
UI_SEARCH_FIELD_HEIGHT = 20

SEARCH_CATEGORY_CMD = '@'
SEARCH_CATEGORY_CMD_RT = '#'
SEARCH_CATEGORY_ALL = '!'
SEARCH_CATEGORY_TOOLS = 'tools'

SPECIAL_SEARCHES = {SEARCH_CATEGORY_CMD, SEARCH_CATEGORY_CMD_RT, SEARCH_CATEGORY_ALL}
SEARCHES_WITHOUT_ALL = {SEARCH_CATEGORY_CMD, SEARCH_CATEGORY_CMD_RT, SEARCH_CATEGORY_TOOLS}
